# permissions to do viewer albums.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: album-viewer-role
rules:
- apiGroups:
  - photos.lynq.peddy.ai
  resources:
  - albums
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - photos.lynq.peddy.ai
  resources:
  - albums/status
  verbs:
  - get
